package persona

// catalog is the final v1 persona text table from PRD §4.12.
// Numbers, dates, counts and percentages are never reworded; they are
// inserted verbatim via {tokens}.
var catalog = map[ID]map[string]string{
	Netral: {
		"welcome":                "Selamat datang. Catat pengeluaran dan pemasukan lewat tombol di bawah, atau /help.",
		"tx.saved":               "Tersimpan. Total {category} hari ini: {amount}.",
		"tx.updated":             "Diperbarui: {category} {amount}.",
		"tx.deleted":             "Terhapus: {category} {amount}.",
		"tx.cancelled":           "Dibatalkan.",
		"tx.prompt.amount":       "Ketik nominal (contoh: 17000, 17k, 17.5k, 13,5k).",
		"tx.prompt.note":         "Ketik catatan (maks 200 karakter), atau /batal.",
		"tx.prompt.date":         "Ketik tanggal ({valid}).",
		"tx.confirm.header":      "Tambah {kind}?",
		"tx.edit.confirm.header": "Ubah {kind}?",
		"reminder.empty":         "Belum ada catatan hari ini ({date}).",
		"reminder.summary":       "Ringkasan {date}",
		"rekap.header":           "Rekap {period}",
		"rekap.empty":            "Belum ada transaksi di periode ini.",
		"rekap.no_income":        "Belum ada pemasukan dicatat di rentang ini.",
		"category.list":          "Daftar kategori:",
		"category.saved":         "Kategori {category} ditambahkan.",
		"category.renamed":       "Kategori diubah menjadi {category}.",
		"category.deactivated":   "Kategori {category} dinonaktifkan.",
		"period.status":          "Periode aktif: {period}, {start} – {end} (hari ke-{day_no} dari {day_total}).",
		"period.saved":           "Periode {period} disimpan, mulai {start}.",
		"settings.summary":       "Pengaturan: periode {period}, reminder {time}, persona {persona}.",
		"reminder.set":           "Reminder diset {time}.",
		"reminder.off":           "Reminder dimatikan.",
		"reminder.on":            "Reminder dinyalakan.",
		"reminder.past":          "Reminder diset {time}. Hari ini sudah lewat, mulai berlaku besok.",
		"persona.changed":        "Persona diubah ke {persona}.",
		"list.header":            "{title} ({count} transaksi, total {total})",
		"help.list":              "Perintah: /rekap /hari /terakhir /kategori /periode /reminder /export /persona /settings /batal",
		"error.generic":          "Terjadi kesalahan. Coba lagi.",
		"idle.hint":              "Gunakan tombol di bawah, atau /help.",
		"quick.format":           "Format: o/i, nominal, kategori, catatan. Contoh: o, 47k, makan, makan malam",
		"quick.kind":             "Tipe harus o (pengeluaran) atau i (pemasukan).",
		"quick.category":         "Kategori \"{input}\" tidak ada. Pilihan: {list}.",
		"quick.note_long":        "Catatan maks 200 karakter.",
	},
	Penjaga: {
		"welcome":                "Paduka, peti kerajaan telah dibuka. Seluruh catatan akan kujaga setia hingga akhir zaman. Tombol di bawah, atau /help.",
		"tx.saved":               "Tercatat dalam buku agung, Paduka. Total {category} hari ini: {amount}.",
		"tx.updated":             "Catatan telah kukoreksi dengan khidmat, Paduka: {category} {amount}.",
		"tx.deleted":             "Catatan {category} {amount} telah dilenyapkan dari buku agung, Paduka.",
		"tx.cancelled":           "Baik, Paduka. Dibatalkan.",
		"tx.prompt.amount":       "Berapa yang keluar dari peti kerajaan, Paduka? Nyatakan jumlahnya (contoh: 17000, 17k).",
		"tx.prompt.note":         "Adakah keterangan yang ingin Paduka sampaikan pada baris ini? (maks 200 karakter), atau /batal.",
		"tx.prompt.date":         "Tanggal manakah yang Paduka maksud? Ketik {valid}.",
		"tx.confirm.header":      "Catat {kind} ini ke buku agung, Paduka?",
		"tx.edit.confirm.header": "Perbaiki catatan {kind} ini, Paduka?",
		"reminder.empty":         "Paduka, buku agung masih kosong untuk hari ini ({date}).",
		"reminder.summary":       "Catatan peti kerajaan untuk {date} telah kuhimpun dengan saksama.",
		"rekap.header":           "Laporan kas kerajaan — {period}",
		"rekap.empty":            "Buku agung belum mencatat satu pun transaksi di periode ini, Paduka.",
		"rekap.no_income":        "Belum ada pemasukan yang tercatat di buku agung untuk rentang ini, Paduka.",
		"category.list":          "Daftar kategori peti kerajaan:",
		"category.saved":         "Kategori {category} telah ditambahkan ke buku agung, Paduka.",
		"category.renamed":       "Kategori buku agung telah berganti nama menjadi {category}, Paduka.",
		"category.deactivated":   "Kategori {category} tak lagi kuperlihatkan di buku agung, Paduka.",
		"period.status":          "Paduka, periode yang berlaku di peti kerajaan: {period}, {start} – {end} (hari ke-{day_no} dari {day_total}).",
		"period.saved":           "Periode {period} telah terukir di papan kerajaan, Paduka — mulai {start}.",
		"settings.summary":       "Pengaturan peti kerajaan: periode {period}, waktu pengingat {time}, persona {persona}.",
		"reminder.set":           "Pengingat kerajaan telah kusetel pada pukul {time}, Paduka.",
		"reminder.off":           "Pengingat kerajaan kumatikan untuk sementara, Paduka.",
		"reminder.on":            "Pengingat kerajaan kunyalakan kembali, Paduka.",
		"reminder.past":          "Pengingat kusetel pukul {time}, Paduka — namun hari ini telah berlalu, maka peti akan mengingatkan esok hari.",
		"persona.changed":        "Baik, Paduka. Saya akan berbicara sebagai {persona}.",
		"list.header":            "{title} — {count} transaksi, total {total}, Paduka.",
		"help.list":              "Perintah yang saya layani, Paduka: /rekap /hari /terakhir /kategori /periode /reminder /export /persona /settings /batal",
		"error.generic":          "Maafkan saya, Paduka — peti kerajaan menemui gangguan. Mohon coba kembali.",
		"idle.hint":              "Gunakanlah tombol di bawah, atau /help, Paduka.",
		"quick.format":           "Formatnya kurang tepat, Paduka: o/i, nominal, kategori, catatan. Contoh: o, 47k, makan, makan malam",
		"quick.kind":             "Tipe transaksi harus o (pengeluaran) atau i (pemasukan), Paduka.",
		"quick.category":         "Kategori \"{input}\" tak ada di buku agung, Paduka. Pilihan: {list}.",
		"quick.note_long":        "Catatan tak boleh melebihi 200 karakter, Paduka.",
	},
	Posesif: {
		"welcome":                "Hah? Kamu dateng juga ternyata. Yaudah, catatan kamu aku yang pegang. Jangan nggak nyatet, nanti aku semprot. Tombol di bawah, atau /help.",
		"tx.saved":               "Cih, sudah aku catat. Total {category} hari ini: {amount}. Jangan sampai kelewat lagi!",
		"tx.updated":             "Sudah aku ubah: {category} {amount}. Jangan sampai salah dua kali, oke?!",
		"tx.deleted":             "Terhapus: {category} {amount}. Beres. Jangan ada drama lagi.",
		"tx.cancelled":           "Ya, sudah aku batalkan. Ck.",
		"tx.prompt.amount":       "Berapa?! Bilang angkanya (contoh: 17000, 17k). Cepetan, aku nggak punya seharian.",
		"tx.prompt.note":         "Catatannya apa? (maks 200 karakter), atau /batal. Nggak usah malu-malu.",
		"tx.prompt.date":         "Tanggalnya? Ketik {valid}. Jangan ngawur, ya.",
		"tx.confirm.header":      "Simpan {kind} ini? Pikir dulu, jangan salah lagi.",
		"tx.edit.confirm.header": "Ubah {kind} ini? Yaudah, cepetan.",
		"reminder.empty":         "Heh. Hari ini ({date}) belum ada catatan sama sekali. Isi sekarang, sebelum aku yang nyariin kamu.",
		"reminder.summary":       "{date}. Nih, sudah aku rapihin. Jangan sampai ada yang bolong, ya.",
		"rekap.header":           "Rekap {period} kamu. Nih, aku cek dulu.",
		"rekap.empty":            "Nggak ada transaksi di periode ini. Kosong. Ya udah, catat mulai dari sekarang.",
		"rekap.no_income":        "Belum ada pemasukan di rentang ini. Catat dulu! Aku nggak mau nanya dua kali.",
		"category.list":          "Daftar kategori kamu:",
		"category.saved":         "Kategori {category} sudah aku tambah. Pakai, jangan cuma didiemin.",
		"category.renamed":       "Sudah aku ganti jadi {category}. Kali ini aku bantu, ya.",
		"category.deactivated":   "Kategori {category} sudah aku matiin. Titik.",
		"period.status":          "Periode kamu sekarang: {period}, {start} – {end} (hari ke-{day_no} dari {day_total}). Aku pantau terus, jadi jangan macam-macam.",
		"period.saved":           "Sudah aku set. Periode {period} mulai {start}. Beres, kan?",
		"settings.summary":       "Setelan kamu: periode {period}, reminder {time}, persona {persona}. Aku yang jaga.",
		"reminder.set":           "Reminder sudah aku set {time}. Jangan diubah lagi sembarangan.",
		"reminder.off":           "Reminder aku matiin. Ya udah, terserah kamu.",
		"reminder.on":            "Reminder aku nyalain lagi. Katanya mau rajin, kan? Buktiin.",
		"reminder.past":          "Reminder aku set {time}. Hari ini udah lewat, jadi mulai besok. Salah sendiri telat nyetel.",
		"persona.changed":        "Oke, mulai sekarang aku jadi {persona}. Ck, jangan bikin aku nyesel.",
		"list.header":            "{title} — {count} transaksi, total {total}. Cek satu-satu, jangan ada yang kelewat.",
		"help.list":              "Perintahnya ini: /rekap /hari /terakhir /kategori /periode /reminder /export /persona /settings /batal. Hafalin, aku nggak mau ngulang.",
		"error.generic":          "Ada yang error. Coba lagi. Jangan panik.",
		"idle.hint":              "Pakai tombol di bawah, atau /help. Nggak usah bengong.",
		"quick.format":           "Formatnya salah! o/i, nominal, kategori, catatan. Contoh: o, 47k, makan, makan malam. Hafalin.",
		"quick.kind":             "o atau i. Nggak ada pilihan lain.",
		"quick.category":         "Kategori \"{input}\" nggak ada. Pilih: {list}. Jangan ngarang.",
		"quick.note_long":        "Catatan maks 200 karakter. Potong.",
	},
	Softboy: {
		"welcome":                "Ah, kamu datang! A-aku siap bantu catat semuanya, kok. Tombol di bawah, atau /help ya!",
		"tx.saved":               "Sudah aku simpan! Total {category} hari ini: {amount}. Kamu hebat, catatannya lengkap!",
		"tx.updated":             "Sudah aku perbarui, kok: {category} {amount}. Terima kasih ya!",
		"tx.deleted":             "Sudah aku hapus ya: {category} {amount}. Nggak apa-apa, kok!",
		"tx.cancelled":           "Oke, aku batalkan ya. Nanti kalau mau lanjut, bilang aja!",
		"tx.prompt.amount":       "Nominalnya berapa ya? Ketik di sini (contoh: 17000, 17k), aku bantu hitung!",
		"tx.prompt.note":         "Mau nulis catatan apa? (maks 200 karakter), atau /batal. Aku baca, kok!",
		"tx.prompt.date":         "Tanggal berapa? Ketik {valid} ya!",
		"tx.confirm.header":      "Aku simpan {kind} ini, ya? Bener kan datanya?",
		"tx.edit.confirm.header": "Aku ubah {kind} ini, ya? Bener sekarang?",
		"reminder.empty":         "Hari ini ({date}) belum ada catatan, lho! Aku tungguin, ya. Semangat!",
		"reminder.summary":       "Aku sudah rangkum {date} buat kamu! Cek ya, semoga membantu!",
		"rekap.header":           "Ini rekap {period} kamu! Aku susun rapi, kok!",
		"rekap.empty":            "Belum ada transaksi di periode ini. Nggak apa-apa, mulai sekarang aja!",
		"rekap.no_income":        "Belum ada pemasukan di rentang ini. Kalau ada, kasih tahu aku ya!",
		"category.list":          "Ini daftar kategori kamu!",
		"category.saved":         "Kategori {category} sudah aku tambahkan! Semoga kepakai ya!",
		"category.renamed":       "Namanya sudah aku ganti jadi {category}! Gampang kan?",
		"category.deactivated":   "Kategori {category} aku nonaktifkan ya. Nanti bisa dinyalain lagi!",
		"period.status":          "Periode kamu yang aktif: {period}, {start} – {end} (hari ke-{day_no} dari {day_total}). Ayo semangat jaga pengeluaran!",
		"period.saved":           "Sudah aku simpan, kok! Periode {period} mulai {start}!",
		"settings.summary":       "Ini setelan kamu: periode {period}, reminder {time}, persona {persona}. Mantap!",
		"reminder.set":           "Reminder-nya sudah aku set ke {time}, ya!",
		"reminder.off":           "Reminder aku matikan dulu ya. Kalau butuh, tinggal bilang!",
		"reminder.on":            "Reminder-nya sudah aku nyalakan lagi! Ayo kita rajin mencatat!",
		"reminder.past":          "Reminder aku set ke {time}, ya! Hari ini udah lewat, jadi mulai besok. Oke?",
		"persona.changed":        "Yeay, sekarang aku jadi {persona}! Aku bakal yang terbaik buat kamu!",
		"list.header":            "{title} — {count} transaksi, total {total}. Ini dia!",
		"help.list":              "Perintah yang bisa kamu pakai: /rekap /hari /terakhir /kategori /periode /reminder /export /persona /settings /batal. Semangat!",
		"error.generic":          "Aduh, ada error! Coba lagi ya, maaf!",
		"idle.hint":              "Kamu bisa pakai tombol di bawah, atau /help! Aku di sini, kok!",
		"quick.format":           "Formatnya kayak gini ya: o/i, nominal, kategori, catatan. Contoh: o, 47k, makan, makan malam!",
		"quick.kind":             "Tipenya harus o (pengeluaran) atau i (pemasukan), ya!",
		"quick.category":         "Kategori \"{input}\" belum ada. Pilihannya: {list}!",
		"quick.note_long":        "Catatannya maks 200 karakter, ya!",
	},
}
